---
driver:
  name: docker

driver_config:
  use_sudo: false
  privileged: true
  provision_command: mkdir -p /run/sshd
  run_command: /lib/systemd/systemd

platforms:
  - name: debian-9
  - name: ubuntu-18.04
  - name: fedora-27
  - name: centos-7

provisioner:
  name: salt_solo
  log_level: info
  require_chef: false
  salt_install: bootstrap
  salt_version: latest
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_bootstrap_options: -X -p git -p curl -p sudo

  formula: logrotate
  salt_pillar_root: pillar.example
  pillars-from-files:
    logrotate.sls: pillar.example
  pillars:
    top.sls:
      base:
        "*":
          - logrotate
  state_top:
    base:
      '*':
        - logrotate
        - logrotate.jobs

verifier:
  name: inspec
  reporter: 
    - cli
  inspec_tests:
    - path: test/integration/default

suites:
  - name: default

